### ISSUE TITLE
CVE whitelisting

### ISSUE THREAD

**Issue by superstator** [digimarc-corp/whalerator#10]
As a user, I want to include a json or yaml formatted list of CVE's with explanatory text and notes with a docker image. This would then be read and merged with scan results from Clair to let other users know that a specific vulnerability has been triaged or addressed in some way for a specific image.

```
CVEs:
- name: CVE-123
  whitelisted: true
  notes: "N/A because reasons"    
```

Maybe this combines with #3 for global whitelisting?
